In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import pickle

In [3]:
data = pd.read_csv('C:/Users/annar/Downloads/sample.csv')
data

   STATION_NAME      DATE   TMAX   TMIN    PRCP
0    PETERSBURG  20100101 -178.0 -311.0     0.0
1    PETERSBURG  20100102 -244.0 -322.0     0.0
2    PETERSBURG  20100103 -194.0 -289.0     0.0
3    PETERSBURG  20100104 -167.0 -200.0    15.0
4    PETERSBURG  20100105 -133.0 -167.0  9999.0
..          ...       ...    ...    ...     ...
88       LONDON  19790127    4.5   -5.2     0.0
89       LONDON  19790128    4.8   -4.4     7.5
90       LONDON  19790129    4.0   -1.0     4.4
91       LONDON  19790130    7.3   -2.6     0.1
92       LONDON  19790131    9.1   -3.1     2.4

[93 rows x 5 columns]

In [4]:
from keras.models import Sequential
from keras.layers import Dense, LSTM

# create the model
model = Sequential()

# add the LSTM layer
model.add(LSTM(50, input_shape=(2, 1)))

# add the output layer
model.add(Dense(1))

# compile the model
model.compile(loss='mean_squared_error', optimizer='adam')

In [5]:
city = input("Enter a city:")
city = city.upper()

In [6]:
date = data[data["STATION_NAME"]==city]["DATE"]
temp_min = data[data["STATION_NAME"]==city]["TMIN"]
temp_max = data[data["STATION_NAME"]==city]["TMAX"]

In [7]:
pred_data = pd.concat([date,temp_max,temp_min],axis=1)
pred_data

        DATE  TMAX  TMIN
62  19790101   2.3  -7.5
63  19790102   1.6  -7.5
64  19790103   1.3  -7.2
65  19790104  -0.3  -6.5
66  19790105   5.6  -1.4
67  19790106   8.3  -6.6
68  19790107   8.5  -5.3
69  19790108   5.8   5.3
70  19790109   5.2   1.6
71  19790110   4.9   1.4
72  19790111   2.9   0.3
73  19790112   2.0  -2.0
74  19790113   4.3  -7.1
75  19790114   6.7  -5.6
76  19790115   5.9   1.0
77  19790116   2.6   4.1
78  19790117   1.9   1.6
79  19790118   3.0  -0.2
80  19790119   7.2  -1.4
81  19790120   3.5  -1.0
82  19790121   1.5  -3.5
83  19790122   0.3  -1.8
84  19790123   2.9  -2.3
85  19790124   5.6  -5.6
86  19790125   2.8  -4.5
87  19790126   1.6  -1.1
88  19790127   4.5  -5.2
89  19790128   4.8  -4.4
90  19790129   4.0  -1.0
91  19790130   7.3  -2.6
92  19790131   9.1  -3.1

In [8]:
pred_data['DATE'] = pd.to_datetime(pred_data.iloc[:,0])

# create a new column for the day of the year (1-365)
pred_data['day_of_year'] = pred_data.iloc[:,0].dt.dayofyear

pred_data['year'] = pred_data.iloc[:,0].dt.year

for i in range (32):
    pred_data['AVG'] = (pred_data.iloc[:,1] + pred_data.iloc[:,2])/2

pred_data

                            DATE  TMAX  TMIN  day_of_year  year   AVG
62 1970-01-01 00:00:00.019790101   2.3  -7.5            1  1970 -2.60
63 1970-01-01 00:00:00.019790102   1.6  -7.5            1  1970 -2.95
64 1970-01-01 00:00:00.019790103   1.3  -7.2            1  1970 -2.95
65 1970-01-01 00:00:00.019790104  -0.3  -6.5            1  1970 -3.40
66 1970-01-01 00:00:00.019790105   5.6  -1.4            1  1970  2.10
67 1970-01-01 00:00:00.019790106   8.3  -6.6            1  1970  0.85
68 1970-01-01 00:00:00.019790107   8.5  -5.3            1  1970  1.60
69 1970-01-01 00:00:00.019790108   5.8   5.3            1  1970  5.55
70 1970-01-01 00:00:00.019790109   5.2   1.6            1  1970  3.40
71 1970-01-01 00:00:00.019790110   4.9   1.4            1  1970  3.15
72 1970-01-01 00:00:00.019790111   2.9   0.3            1  1970  1.60
73 1970-01-01 00:00:00.019790112   2.0  -2.0            1  1970  0.00
74 1970-01-01 00:00:00.019790113   4.3  -7.1            1  1970 -1.40
75 1970-01-01 00:00:00.019790114   6.7  -5.6            1  1970  0.55
76 1970-01-01 00:00:00.019790115   5.9   1.0            1  1970  3.45
77 1970-01-01 00:00:00.019790116   2.6   4.1            1  1970  3.35
78 1970-01-01 00:00:00.019790117   1.9   1.6            1  1970  1.75
79 1970-01-01 00:00:00.019790118   3.0  -0.2            1  1970  1.40
80 1970-01-01 00:00:00.019790119   7.2  -1.4            1  1970  2.90
81 1970-01-01 00:00:00.019790120   3.5  -1.0            1  1970  1.25
82 1970-01-01 00:00:00.019790121   1.5  -3.5            1  1970 -1.00
83 1970-01-01 00:00:00.019790122   0.3  -1.8            1  1970 -0.75
84 1970-01-01 00:00:00.019790123   2.9  -2.3            1  1970  0.30
85 1970-01-01 00:00:00.019790124   5.6  -5.6            1  1970  0.00
86 1970-01-01 00:00:00.019790125   2.8  -4.5            1  1970 -0.85
87 1970-01-01 00:00:00.019790126   1.6  -1.1            1  1970  0.25
88 1970-01-01 00:00:00.019790127   4.5  -5.2            1  1970 -0.35
89 1970-01-01 00:00:00.019790128   4.8  -4.4            1  1970  0.20
90 1970-01-01 00:00:00.019790129   4.0  -1.0            1  1970  1.50
91 1970-01-01 00:00:00.019790130   7.3  -2.6            1  1970  2.35
92 1970-01-01 00:00:00.019790131   9.1  -3.1            1  1970  3.00

In [9]:
train, test = train_test_split(pred_data, test_size=0.2, random_state=42)

train_X = train[['day_of_year', 'year']]
train_y = train['AVG']

test_X = test[['day_of_year', 'year']]
test_y = test['AVG']

In [10]:
train_X = train_X.values.reshape((train_X.shape[0], 2, 1))
test_X = test_X.values.reshape((test_X.shape[0], 2, 1))

In [11]:
model.fit(train_X, train_y, epochs=50, batch_size=72, validation_data=(test_X, test_y), verbose=2)

s = input("Enter Start Date: ")
s = pd.to_datetime(s)

e = input("Enter End Date: ")
e = pd.to_datetime(e)


# create a new dataframe for the future dates
future_dates = pd.date_range(start= s, end= e)
future_data = pd.DataFrame({'date': future_dates})

# create the day of year and year columns for the future dates
future_data['day_of_year'] = future_data['date'].dt.dayofyear
future_data['year'] = future_data['date'].dt.year

# make predictions using the model
future_X = future_data[['day_of_year', 'year']]
future_X = future_X.values.reshape((future_X.shape[0], 2, 1))
future_y = model.predict(future_X)

# add the predicted temperatures to the dataframe
future_data['temperature'] = future_y

# print the predicted temperatures
print(future_data['temperature'])

Epoch 1/50
1/1 - 2s - loss: 4.7946 - val_loss: 5.0948 - 2s/epoch - 2s/step
Epoch 2/50
1/1 - 0s - loss: 4.7883 - val_loss: 5.0624 - 29ms/epoch - 29ms/step
Epoch 3/50
1/1 - 0s - loss: 4.7837 - val_loss: 5.0310 - 28ms/epoch - 28ms/step
Epoch 4/50
1/1 - 0s - loss: 4.7793 - val_loss: 4.9967 - 32ms/epoch - 32ms/step
Epoch 5/50
1/1 - 0s - loss: 4.7748 - val_loss: 4.9510 - 32ms/epoch - 32ms/step
Epoch 6/50
1/1 - 0s - loss: 4.7689 - val_loss: 4.8689 - 36ms/epoch - 36ms/step
Epoch 7/50
1/1 - 0s - loss: 4.7591 - val_loss: 4.7007 - 33ms/epoch - 33ms/step
Epoch 8/50
1/1 - 0s - loss: 4.7422 - val_loss: 4.4473 - 24ms/epoch - 24ms/step
Epoch 9/50
1/1 - 0s - loss: 4.7253 - val_loss: 4.2652 - 32ms/epoch - 32ms/step
Epoch 10/50
1/1 - 0s - loss: 4.7204 - val_loss: 4.1909 - 25ms/epoch - 25ms/step
Epoch 11/50
1/1 - 0s - loss: 4.7202 - val_loss: 4.1587 - 32ms/epoch - 32ms/step
Epoch 12/50
1/1 - 0s - loss: 4.7205 - val_loss: 4.1397 - 32ms/epoch - 32ms/step
Epoch 13/50
1/1 - 0s - loss: 4.7208 - val_loss: 4.1260 - 24ms/epoch - 24ms/step
Epoch 14/50
1/1 - 0s - loss: 4.7211 - val_loss: 4.1150 - 32ms/epoch - 32ms/step
Epoch 15/50
1/1 - 0s - loss: 4.7213 - val_loss: 4.1062 - 32ms/epoch - 32ms/step
Epoch 16/50
1/1 - 0s - loss: 4.7215 - val_loss: 4.0992 - 32ms/epoch - 32ms/step
Epoch 17/50
1/1 - 0s - loss: 4.7217 - val_loss: 4.0940 - 34ms/epoch - 34ms/step
Epoch 18/50
1/1 - 0s - loss: 4.7218 - val_loss: 4.0902 - 39ms/epoch - 39ms/step
Epoch 19/50
1/1 - 0s - loss: 4.7219 - val_loss: 4.0876 - 40ms/epoch - 40ms/step
Epoch 20/50
1/1 - 0s - loss: 4.7220 - val_loss: 4.0862 - 40ms/epoch - 40ms/step
Epoch 21/50
1/1 - 0s - loss: 4.7221 - val_loss: 4.0858 - 40ms/epoch - 40ms/step
Epoch 22/50
1/1 - 0s - loss: 4.7221 - val_loss: 4.0864 - 81ms/epoch - 81ms/step
Epoch 23/50
1/1 - 0s - loss: 4.7221 - val_loss: 4.0879 - 33ms/epoch - 33ms/step
Epoch 24/50
1/1 - 0s - loss: 4.7220 - val_loss: 4.0902 - 24ms/epoch - 24ms/step
Epoch 25/50
1/1 - 0s - loss: 4.7219 - val_loss: 4.0933 - 32ms/epoch - 32ms/step
Epoch 26/50
1/1 - 0s - loss: 4.7219 - val_loss: 4.0969 - 40ms/epoch - 40ms/step
Epoch 27/50
1/1 - 0s - loss: 4.7218 - val_loss: 4.1011 - 40ms/epoch - 40ms/step
Epoch 28/50
1/1 - 0s - loss: 4.7217 - val_loss: 4.1059 - 32ms/epoch - 32ms/step
Epoch 29/50
1/1 - 0s - loss: 4.7215 - val_loss: 4.1110 - 33ms/epoch - 33ms/step
Epoch 30/50
1/1 - 0s - loss: 4.7214 - val_loss: 4.1165 - 40ms/epoch - 40ms/step
Epoch 31/50
1/1 - 0s - loss: 4.7213 - val_loss: 4.1226 - 34ms/epoch - 34ms/step
Epoch 32/50
1/1 - 0s - loss: 4.7211 - val_loss: 4.1299 - 31ms/epoch - 31ms/step
Epoch 33/50
1/1 - 0s - loss: 4.7210 - val_loss: 4.1415 - 32ms/epoch - 32ms/step
Epoch 34/50
1/1 - 0s - loss: 4.7208 - val_loss: 4.1699 - 32ms/epoch - 32ms/step
Epoch 35/50
1/1 - 0s - loss: 4.7204 - val_loss: 4.2513 - 32ms/epoch - 32ms/step
Epoch 36/50
1/1 - 0s - loss: 4.7202 - val_loss: 4.2493 - 40ms/epoch - 40ms/step
Epoch 37/50
1/1 - 0s - loss: 4.7202 - val_loss: 4.2104 - 32ms/epoch - 32ms/step
Epoch 38/50
1/1 - 0s - loss: 4.7201 - val_loss: 4.1940 - 32ms/epoch - 32ms/step
Epoch 39/50
1/1 - 0s - loss: 4.7202 - val_loss: 4.1925 - 40ms/epoch - 40ms/step
Epoch 40/50
1/1 - 0s - loss: 4.7202 - val_loss: 4.1985 - 32ms/epoch - 32ms/step
Epoch 41/50
1/1 - 0s - loss: 4.7202 - val_loss: 4.2109 - 32ms/epoch - 32ms/step
Epoch 42/50
1/1 - 0s - loss: 4.7201 - val_loss: 4.2288 - 40ms/epoch - 40ms/step
Epoch 43/50
1/1 - 0s - loss: 4.7201 - val_loss: 4.2407 - 40ms/epoch - 40ms/step
Epoch 44/50
1/1 - 0s - loss: 4.7202 - val_loss: 4.2341 - 40ms/epoch - 40ms/step
Epoch 45/50
1/1 - 0s - loss: 4.7202 - val_loss: 4.2211 - 40ms/epoch - 40ms/step
Epoch 46/50
1/1 - 0s - loss: 4.7201 - val_loss: 4.2123 - 32ms/epoch - 32ms/step
Epoch 47/50
1/1 - 0s - loss: 4.7201 - val_loss: 4.2081 - 32ms/epoch - 32ms/step
Epoch 48/50
1/1 - 0s - loss: 4.7202 - val_loss: 4.2069 - 40ms/epoch - 40ms/step
Epoch 49/50
1/1 - 0s - loss: 4.7202 - val_loss: 4.2076 - 40ms/epoch - 40ms/step
Epoch 50/50
1/1 - 0s - loss: 4.7202 - val_loss: 4.2095 - 33ms/epoch - 33ms/step
1/1 [==============================] - 0s 350ms/step
0    0.558525
1    0.557137
2    0.555798
3    0.554502
Name: temperature, dtype: float32

In [12]:
Pkl_file = 'pickle_model'
with open(Pkl_file, 'wb') as file:
    pickle.dump(model,file)

Keras weights file (<HDF5 file "variables.h5" (mode r+)>) saving:
...layers\dense
......vars
.........0
.........1
...layers\lstm
......vars
...layers\lstm\cell
......vars
.........0
.........1
.........2
...metrics\mean
......vars
.........0
.........1
...optimizer
......vars
.........0
.........1
.........10
.........2
.........3
.........4
.........5
.........6
.........7
.........8
.........9
...vars
Keras model archive saving:
File Name                                             Modified             Size
config.json                                    2023-03-05 14:15:38         1800
metadata.json                                  2023-03-05 14:15:38           64
variables.h5                                   2023-03-05 14:15:38       143648

In [13]:
Pkl_file = 'pickle_model'
with open(Pkl_file, 'rb') as file:
    predictor=pickle.load(file)

Keras model archive loading:
File Name                                             Modified             Size
config.json                                    2023-03-05 14:15:38         1800
metadata.json                                  2023-03-05 14:15:38           64
variables.h5                                   2023-03-05 14:15:38       143648
Keras weights file (<HDF5 file "variables.h5" (mode r)>) loading:
...layers\dense
......vars
.........0
.........1
...layers\lstm
......vars
...layers\lstm\cell
......vars
.........0
.........1
.........2
...metrics\mean
......vars
.........0
.........1
...optimizer
......vars
.........0
.........1
.........10
.........2
.........3
.........4
.........5
.........6
.........7
.........8
.........9
...vars